## Numpy array and basics
learn about numpy with chai aur code

In [6]:
import numpy as np

creating array from list

In [8]:
arr_1d = np.array([1,2,3,4,5])
print("1D array: ", arr_1d)

arr_2d = np.array([[1,2,3], [4,5,6]])
print("2D array: ", arr_2d)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


## List vs numpy array

In [15]:
py_list = [1,2,3] # element wise multiplication
print("Python list multiplication: ", py_list * 2)

np_list = np.array([1,2,3])
print("Numpy array multiplication: ", np_list * 2)

import time
start = time.time()
py_list = [i * 2 for i in range(1000000)]
print("\nList operation time: ", time.time() - start)

start = time.time()
np_list = np.arange(1000000) * 2
print("Numpy array operation time: ", time.time() - start)

Python list multiplication:  [1, 2, 3, 1, 2, 3]
Numpy array multiplication:  [2 4 6]

List operation time:  0.0626227855682373
Numpy array operation time:  0.00396275520324707


creating array from scratch

In [22]:
zeors = np.zeros((3, 4))
print("zeors array: \n", zeors)

ones = np.ones((2, 3))
print("one array: \n", ones)

full = np.full((2,2), 7)
print("full array: \n", full)

random = np.random.random((2,2))
print("random array: \n", random)

sequence = np.arange(0, 10, 2)
print("sequence array: \n", sequence)

zeors array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
one array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.94234372 0.39622331]
 [0.05149509 0.10439772]]
sequence array: 
 [0 2 4 6 8]


## Vector, Matrix and Tensor

In [9]:
vector = np.array([1, 2, 3])
print("Vector: ", vector)

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("Matrix: \n", matrix)

tensor = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])
print("Tensor: \n", tensor)

Vector:  [1 2 3]
Matrix: 
 [[1 2 3]
 [4 5 6]]
Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [16]:
arr = np.array([[1, 2, 3],
               [4, 5, True]])
print("Array ", arr)
print("Shape ", arr.shape)
print("Dimension ", arr.ndim)
print("Size ", arr.size)
print("Data type ", arr.dtype)
print("Item size ", arr.itemsize)
print("Total size ", arr.nbytes)
print("Flags ", arr.flags)

Array  [[1 2 3]
 [4 5 1]]
Shape  (2, 3)
Dimension  2
Size  6
Data type  int64
Item size  8
Total size  48
Flags    C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



### Array Reshaping

In [22]:
arr = np.arange(12)
print("Original array: ", arr)

reshaped = arr.reshape((3, 4))
print("\nReshaped array: ", reshaped)

flattened = reshaped.flatten()
print("\nFlattened array: ", flattened)

# ravel (return view, instead of copy)
raveled = reshaped.ravel()
print("\nRaveled array: ", raveled)

# Transpose 
transpose = reshaped.T
print("\nTransposed array: ", transpose)


Original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Raveled array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Transposed array:  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
