## Numpy Array opeations

In [1]:
import numpy as np

In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic Slicing: ", arr[2:7])
print("With Step: ", arr[1:8:3])
print("Negative Indexing: ", arr[-3])

Basic Slicing:  [3 4 5 6 7]
With Step:  [2 5 8]
Negative Indexing:  8


In [13]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6], 
                   [7, 8, 9]])
print("Specific Element: ", arr_2d[1, 2])
print("Specific Element: ", arr_2d[1])
print("Entire row: ", arr_2d[1, :])
print("Entire column: ", arr_2d[:, 1])

Specific Element:  6
Specific Element:  [4 5 6]
Entire row:  [4 5 6]
Entire column:  [2 5 8]


## Sorting

In [20]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Sorted Array: ", np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 1], 
                            [1, 2],
                            [2, 3]])
print("Sorted 2D array by column: ", np.sort(arr_2d_unsorted, axis = 0))
print("Sorted 2D array by row: ", np.sort(arr_2d_unsorted, axis = 1))

Sorted Array:  [1 1 2 3 4 5 6 9]
Sorted 2D array by column:  [[1 1]
 [2 2]
 [3 3]]
Sorted 2D array by row:  [[1 3]
 [1 2]
 [2 3]]


## Filter

In [22]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

even_number = numbers[numbers % 2 == 0]
print("Even numbers: ", even_number)

Even numbers:  [ 2  4  6  8 10]


## Filter with mask

In [25]:
mask = numbers > 5 
print("Number greater than 5: ", numbers[mask])

Number greater than 5:  [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [30]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print("Where: ", where_result)
print("NP where: ", numbers[where_result])

[1 3 5]
Where:  (array([5, 6, 7, 8, 9]),)
NP where:  [ 6  7  8  9 10]


In [34]:
# condition_array = np.where(numbers > 5, numbers * 2, numbers)
condition_array = np.where(numbers > 5, "true", "false")
print(condition_array)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


## Adding and removing data

In [37]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = arr1 + arr2
print("Don't do it. It will add elements: ", combined)

combined = np.concatenate((arr1, arr2))
print("Concatenate: ", combined)

Don't do it. It will add elements:  [5 7 9]
Concatenate:  [1 2 3 4 5 6]


## array compatibility

In [41]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 7])
c = np.array([7, 8, 9])

print("Compatibility shapes: ", a.shape == b.shape)
print("Compatibility shapes: ", a.shape == c.shape)

Compatibility shapes:  False
Compatibility shapes:  True


In [44]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([5, 6])

with_new_row = np.vstack((original, new_row))
print(original)
print(with_new_row)

new_col = np.array([[7], [8]])

with_new_col = np.hstack((original, new_col))
print(original)
print(with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]]
[[1 2 7]
 [3 4 8]]


In [46]:
arr = np.array([1, 2, 3, 4, 5])
delete = np.delete(arr, 2)

print("Array after deletion: ", delete)
print("Original array: ", arr)

Array after deletion:  [1 2 4 5]
Original array:  [1 2 3 4 5]
